<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_29</name>
   <tag></tag>
   <elementGuidId>cf5b1fa6-8daf-417e-b5ba-e1bdba17f3df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='29']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#29</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>52acb8f9-a8fd-40ec-ab11-f926f71a1b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>29</value>
      <webElementGuid>39dcc370-0e55-4a4d-bb9b-758181fd543a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>fcad8e27-e1f3-4229-8171-4f9cf0972632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>dd6ffc17-1ad8-4ccd-924a-441f3f00cdf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=5400</value>
      <webElementGuid>ebfbc232-d408-46de-80f1-4438b66c1155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=5400</value>
      <webElementGuid>1e994ee4-23b1-4bf5-8ab5-bf6349866c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;29&quot;)</value>
      <webElementGuid>9e99a10a-63d5-4247-8cfb-df05db436875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='29']</value>
      <webElementGuid>e67c2f70-13c7-4787-9eb5-e6299363b582</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>3cd319be-821f-4623-abea-04f3377d88cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '29' and @src = '/catalog/fetchImage?image_id=5400']</value>
      <webElementGuid>76b88846-21e3-4f07-9ae7-85c0babc4f4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
