<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CHECKOUT (1,660.98)</name>
   <tag></tag>
   <elementGuidId>b891782e-814b-4b6e-a46a-91a608bf5e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='checkOutButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#checkOutButton</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1c4b8257-4911-4138-aa80-c9de00e65f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f93a977f-3adc-4b75-a673-7098018b8bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium tami uft-class ng-binding</value>
      <webElementGuid>321cd6df-1002-4aa4-b9d4-a6a567f6a87c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>checkout()</value>
      <webElementGuid>7ecc4b31-bb30-4e67-b9f6-3eff6b838231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkOutButton</value>
      <webElementGuid>94b9f943-1f9f-4fba-ace8-e780312459a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>check_out_btn</value>
      <webElementGuid>c0d07489-22a6-45eb-9d66-8f27b8edc002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CHECKOUT ($1,660.98)</value>
      <webElementGuid>6f548d94-5db5-4e95-81d6-c53c2437a4e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;checkOutButton&quot;)</value>
      <webElementGuid>afdc83ce-1935-4ad6-b4a3-842096ebe621</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='checkOutButton']</value>
      <webElementGuid>b4479119-5fb1-41aa-ad4d-d31f68f7e189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>6542a987-1fe2-4f61-be0b-547bac3670e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$1,660.98'])[2]/following::button[1]</value>
      <webElementGuid>d179b7d4-a226-4ec4-b2cb-c18688d23748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TOTAL:'])[1]/following::button[1]</value>
      <webElementGuid>bf4b79c0-b818-430e-a9dd-19c45fefb774</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your shopping cart is empty'])[2]/preceding::button[1]</value>
      <webElementGuid>0f767e43-8d81-4617-881a-fe7a964af3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUE SHOPPING'])[1]/preceding::button[1]</value>
      <webElementGuid>0d1ec7a2-7f87-4f7a-acb6-56046f6d637e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/table/tfoot/tr[2]/td/button</value>
      <webElementGuid>99f23196-1c95-4517-80a4-61c1691d69d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'checkOutButton' and @name = 'check_out_btn' and (text() = 'CHECKOUT ($1,660.98)' or . = 'CHECKOUT ($1,660.98)')]</value>
      <webElementGuid>a0070ff6-6d09-431f-9f18-677aa896efc5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
