<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_View Details_popular_item_10_img</name>
   <tag></tag>
   <elementGuidId>7efbb93a-d7eb-45d6-ba1e-3f6ed5b2c07a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='popular_item_10_img']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;popular_item_10_img&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ce33bc5d-7e14-4d1b-a834-ff7ad11d5d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>popular_item_10_img</value>
      <webElementGuid>1deff5c1-f69c-4ae8-976a-e1ec1960b9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>css/images/Popular-item2.jpg</value>
      <webElementGuid>60dd5241-f302-4be0-a849-4cacbeda8490</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Special-offer</value>
      <webElementGuid>12a76923-bdb6-4dd6-839e-3bf0e0ac1103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>9f053e3e-f6e0-4f0a-9b9d-7541632958a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>e5b57779-9f2b-4ee5-bfab-6f65d7163dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/Popular-item2.jpg</value>
      <webElementGuid>9573a10c-deae-4700-99d4-80d2d760ac0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;popular_items&quot;)/div[@class=&quot;grid-table center&quot;]/div[@class=&quot;ng-scope&quot;]/figure[1]/img[1]</value>
      <webElementGuid>9039def2-b64f-4362-a7cb-d8395550107a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='popular_item_10_img']</value>
      <webElementGuid>7e9e99b7-c404-41f5-9392-6e9b4c9e5220</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[2]/figure/img</value>
      <webElementGuid>104528f8-4179-499b-8e2b-bcb56fb03aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Special-offer'])[3]</value>
      <webElementGuid>dacd5631-4095-460b-a42a-ac6e8204e467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/figure/img</value>
      <webElementGuid>9b907770-d839-4a3d-849a-034bd0f4a68b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'popular_item_10_img' and @alt = 'Special-offer' and @href = 'javascript:void(0)' and @src = 'css/images/Popular-item2.jpg']</value>
      <webElementGuid>5b289d2d-bfa4-42c2-8ca8-01cc527e0bfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
