<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_View Details</name>
   <tag></tag>
   <elementGuidId>a38fa4e8-b2fd-4fd6-814b-8f3edd03cd6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='details_10']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#details_10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>732d3f96-168c-4ba2-b538-3cc26d6842cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>details_10</value>
      <webElementGuid>4284676d-ac8b-4f3c-bc41-935dadb068b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>shop_nowSub viewDetail ng-scope</value>
      <webElementGuid>1fb9ac49-9202-45e0-a056-87f094001824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>View_details</value>
      <webElementGuid>07b9f2ff-5c19-4367-877f-ff68c27a39ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Details</value>
      <webElementGuid>ac9e45ed-6ff0-484b-98f7-aad501c63d9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;details_10&quot;)</value>
      <webElementGuid>b48c6abd-f188-4b9e-bebf-53803d651ded</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='details_10']</value>
      <webElementGuid>013f8882-3d61-4247-b877-f2210df17f8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='popular_items']/div/div[2]/a/label</value>
      <webElementGuid>230f067d-631e-4f0b-b856-6878d6051264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[1]/following::label[1]</value>
      <webElementGuid>34831c2a-02ac-45fc-9f85-495c30ede5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POPULAR ITEMS'])[2]/following::label[2]</value>
      <webElementGuid>64fd7c8b-c826-40ca-9fd2-3c88d5252076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View Details'])[3]/preceding::label[1]</value>
      <webElementGuid>fb16f1d0-ebf4-4e3b-9be8-1944010bfd3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHAT WITH US'])[1]/preceding::label[2]</value>
      <webElementGuid>f0fb5c87-1cc0-464c-912c-83eb53dac300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/label</value>
      <webElementGuid>d167ca21-734d-4bfb-9b53-8f4aa9fec20d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'details_10' and (text() = 'View Details' or . = 'View Details')]</value>
      <webElementGuid>877ffd90-750f-465e-afcf-a0a3df1dd5ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
