<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT  (0.00)_hrefUserIcon</name>
   <tag></tag>
   <elementGuidId>405e5e04-1916-4eec-adff-c6a8b1deb8f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hrefUserIcon']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#hrefUserIcon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>01fa1d78-3ed1-46fb-b788-fa91e308df6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrefUserIcon</value>
      <webElementGuid>06cbe821-0abc-446e-aa24-e675e332ed2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>USER</value>
      <webElementGuid>dbb0510e-af12-4388-bc78-c0d1783af09e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrefUserIcon&quot;)</value>
      <webElementGuid>7758b88b-0b3a-414a-b40a-0cdb10082b4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hrefUserIcon']</value>
      <webElementGuid>8ca027ab-207f-4195-ab82-7c6b5b0329eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/a</value>
      <webElementGuid>3d0e9f0a-4fc4-4c41-b352-92cf511e99d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[2]</value>
      <webElementGuid>30acf0ee-96bf-4817-b33a-687cb3342f2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::a[1]</value>
      <webElementGuid>18238c8f-ac4a-47e6-a2b5-180834bdfdf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::a[1]</value>
      <webElementGuid>b8eba7f7-c4b2-42c5-ae46-986c532bd4a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/a</value>
      <webElementGuid>9c5c8c74-46fd-4dca-a002-3bc85fa98017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'hrefUserIcon' and @title = 'USER']</value>
      <webElementGuid>433bd2ac-22d6-4e16-a5a6-0deb3785bdc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
