<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_EDIT_1</name>
   <tag></tag>
   <elementGuidId>948ea3a1-3e96-41d7-a0a1-198d77e808e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shoppingCart']/table/tbody/tr[2]/td[6]/span/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>41273b96-4099-427f-803b-4a227440cd3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>edit ng-scope</value>
      <webElementGuid>71bae20a-687f-46bf-856a-0283ad207dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/product/10?color=C3C3C3&amp;quantity=1&amp;pageState=edit&amp;warranty=</value>
      <webElementGuid>329103f1-a2d8-4090-9dcd-df7c6b452cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>d3bf329d-3b1d-4a39-9829-65d18b77d144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>EDIT</value>
      <webElementGuid>b801af82-2dd8-499d-b36f-15c427c104ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shoppingCart&quot;)/table[@class=&quot;fixedTableEdgeCompatibility&quot;]/tbody[1]/tr[@class=&quot;ng-scope&quot;]/td[@class=&quot;smollCell&quot;]/span[@class=&quot;actions&quot;]/a[@class=&quot;edit ng-scope&quot;]</value>
      <webElementGuid>71a87cf2-4a7c-48e1-8ff3-f7a95441ed1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shoppingCart']/table/tbody/tr[2]/td[6]/span/a</value>
      <webElementGuid>bdb58673-c180-424a-97c8-7713d8b9c757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'EDIT')])[2]</value>
      <webElementGuid>e043c018-cc13-43f0-9dab-b43a102f1990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRICE:'])[2]/following::a[1]</value>
      <webElementGuid>fcc777e0-c557-4609-af34-4981fa4259ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUANTITY'])[3]/following::a[1]</value>
      <webElementGuid>bfb55fdf-3cd6-403b-87ad-358f3a196066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[2]/preceding::a[1]</value>
      <webElementGuid>c7eb4d9b-dafd-42f7-864d-158817b6cce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REMOVE'])[2]/preceding::a[2]</value>
      <webElementGuid>04c24e2b-ef6a-4c31-8fa2-a1564a69a2e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#/product/10?color=C3C3C3&amp;quantity=1&amp;pageState=edit&amp;warranty=')]</value>
      <webElementGuid>00e62082-4b2f-4414-9ff9-dd0a1869b817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]/span/a</value>
      <webElementGuid>093b189f-9247-4ccb-820b-80075ab02f8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/product/10?color=C3C3C3&amp;quantity=1&amp;pageState=edit&amp;warranty=' and (text() = 'EDIT' or . = 'EDIT')]</value>
      <webElementGuid>6f0a5267-aab1-4312-b22d-7dec5a1afde4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
