<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_9</name>
   <tag></tag>
   <elementGuidId>f2a1ddc6-8eff-4caf-bfd9-e51f47975174</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='9']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#9</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>417db57a-4d6c-4941-a4f5-030cdc199198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>fba6cd58-c4df-425e-b69a-b5917441a9e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>87606974-02d4-4af5-946e-fe26c73e5ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>7c7cbe62-c32a-4f4b-95b9-f0789d254b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=1249</value>
      <webElementGuid>0dea33d0-8b50-45c8-8c81-07994171ce6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=1249</value>
      <webElementGuid>53e50423-796a-4527-96d2-ad0dab1e55a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;9&quot;)</value>
      <webElementGuid>f86ff1b7-d848-4a0e-8e3c-33703f4952a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='9']</value>
      <webElementGuid>57bd2335-f73a-44aa-b29e-41112850dd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>7d6eb4a5-f5dc-407d-9d74-499c3f812d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '9' and @src = '/catalog/fetchImage?image_id=1249']</value>
      <webElementGuid>3b53c295-199c-4ed7-bdaf-b076fcda6d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
