<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_COLOR</name>
   <tag></tag>
   <elementGuidId>2b53d41e-958d-4bc0-afc7-5af78e94594c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionColor']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accordionColor</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>7c8f5505-a2c0-46d1-a2e8-d40b7a8a4f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>daeec801-d4c8-40a4-a8de-4792835b5c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-scope</value>
      <webElementGuid>f9577132-0bd5-4e95-9b13-b03b26ff40f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionColor</value>
      <webElementGuid>4a53bc87-67ca-4a5b-9294-12fd50d0cd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionColor')</value>
      <webElementGuid>ba9cd1d1-1adc-4df9-a3d6-abc56305ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>COLOR</value>
      <webElementGuid>51b39531-2dbb-4d3a-823f-922ca2561340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>7d67de5f-c19a-4b1f-ae25-8c74aa029e0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>COLOR</value>
      <webElementGuid>56515462-68e8-4bc7-8333-a4b086b04b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionColor&quot;)</value>
      <webElementGuid>b0dce220-325f-491d-bdfa-d2240cb1f151</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionColor']</value>
      <webElementGuid>7b10cd05-da45-4bdb-80a0-f8cfb87e516d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[6]/h4</value>
      <webElementGuid>51103348-34da-4470-bf49-e75a444661b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bluetooth®'])[1]/following::h4[1]</value>
      <webElementGuid>ac7ec709-5da9-4d2b-869f-2d1b07155c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bluetooh®'])[1]/following::h4[1]</value>
      <webElementGuid>c2ff19f0-a658-4532-867c-4080cad3c16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOLD OUT'])[1]/preceding::h4[1]</value>
      <webElementGuid>f3faf321-bda7-4208-8e34-2277abc4dfdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOP NOW'])[1]/preceding::h4[1]</value>
      <webElementGuid>64b4fe71-e174-4ec3-a37c-52c47a3e5457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='COLOR']/parent::*</value>
      <webElementGuid>52abfe0c-5aef-4a82-93db-aacc03e21959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[6]/h4</value>
      <webElementGuid>5bace149-4af7-428e-9730-8a80cac03ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionColor' and (text() = 'COLOR' or . = 'COLOR')]</value>
      <webElementGuid>f4e1a94e-4c50-4fa7-acce-6e323cd9c99a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
