<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEE OFFER</name>
   <tag></tag>
   <elementGuidId>3accb1f6-10af-4940-ad48-f17a322f069b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#see_offer_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='see_offer_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a74f3ecc-bcd1-4cee-a369-d36117dc4de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>see_offer_btn</value>
      <webElementGuid>fcb39b70-ad07-4475-aae3-18db9d958d79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>SEE_OFFER</value>
      <webElementGuid>22cb4455-8771-4828-b6a5-af783de0acc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3801cdc-e959-49a9-8b99-ff991d84f602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>55fe6aed-11a5-41cc-a3c7-507cdb953c80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEE OFFER</value>
      <webElementGuid>c347da1c-c368-4db5-b811-db808af87270</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;see_offer_btn&quot;)</value>
      <webElementGuid>68f721e4-8d50-4e55-8070-712128c935fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='see_offer_btn']</value>
      <webElementGuid>1655297f-a251-4626-b12b-38f11f271d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-special-offer']/div/a/button</value>
      <webElementGuid>107dffdc-5bab-491b-bcdc-da00a88fde39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/following::button[1]</value>
      <webElementGuid>8f417953-85ce-4c9e-8a12-cbd5f45ee51f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/following::button[1]</value>
      <webElementGuid>6a54996b-6f81-46c7-91c0-9a1071bc76bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[1]/preceding::button[1]</value>
      <webElementGuid>66e6bdbc-29c9-4345-b88a-00dd0d1f7818</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[1]/preceding::button[1]</value>
      <webElementGuid>225cb08a-ffc0-4369-8957-fefb2b227439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEE OFFER']/parent::*</value>
      <webElementGuid>c98db8af-07d0-42be-9e17-1b121bb54093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>0b185b00-72f2-4e8c-9db8-342db9cda929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'see_offer_btn' and (text() = 'SEE OFFER' or . = 'SEE OFFER')]</value>
      <webElementGuid>8a8296c6-e00f-4d5b-9e4d-a22aede03c06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
