<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FOLLOW US_follow_facebook</name>
   <tag></tag>
   <elementGuidId>c72ab5bc-6cd7-4e55-acfb-16aa10637032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_facebook']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_facebook&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>072c2cba-14a0-409b-ae73-81e8ba0638c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_facebook</value>
      <webElementGuid>4b65fb49-f45a-488f-a64b-ca270dc083fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/facebook.png</value>
      <webElementGuid>8c8bf896-5171-4288-92dd-a4b28fc119fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>78aa640d-eb18-4fc0-8b06-565e3d97e682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>linkTo('')</value>
      <webElementGuid>c41e4bb2-24f7-42a5-8ced-fdd5f120589e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[1]/img[1]</value>
      <webElementGuid>fa01522b-adca-40a5-920e-ea849c72f454</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_facebook']</value>
      <webElementGuid>9c911591-6492-4031-ad47-c8eb96bf9a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a/img</value>
      <webElementGuid>41bccd37-5d1b-4c72-88f0-ba5c29ca227f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='icon']</value>
      <webElementGuid>d1c09b77-667c-4357-8b0c-3fd17bd56d2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/a/img</value>
      <webElementGuid>2f302d33-8e1d-438f-be9d-d5b15c4a7508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_facebook' and @src = 'css/images/facebook.png' and @alt = 'icon']</value>
      <webElementGuid>6bc814a6-1bd4-4d55-a151-3d36c3c2263a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
