<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FOLLOW US_follow_linkedin</name>
   <tag></tag>
   <elementGuidId>bb87a838-f265-4891-935d-78f7bb87dd2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_linkedin']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_linkedin&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5b6c701-bcf0-45b8-b273-2068b1cf60a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_linkedin</value>
      <webElementGuid>f2d103b6-f118-49c4-9fe4-70755cc0a636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/linkedin.png</value>
      <webElementGuid>e84baee7-7afa-4f10-9ade-b15a0ebee5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>49ea29b0-df53-480c-ae86-b88fac9a0ecb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[3]/img[1]</value>
      <webElementGuid>617e4f6c-1c61-438b-a220-dd9a743ce2f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_linkedin']</value>
      <webElementGuid>ad485dc4-9cbd-488e-afa9-4a6a273c4172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a[3]/img</value>
      <webElementGuid>e2095c1d-599a-47a2-8163-fd3861695746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[3]</value>
      <webElementGuid>cff17080-2521-4815-b103-b2eeab8da3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>17308180-af18-4a08-91c1-fc32ea3b494b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_linkedin' and @src = 'css/images/linkedin.png' and @alt = 'icon']</value>
      <webElementGuid>8b5de604-2689-4124-a568-a73647fe88d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
