<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_DEMO_go_up_btn</name>
   <tag></tag>
   <elementGuidId>611ae910-18b9-4d73-a645-41bade4921a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='go_up_btn']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;go_up_btn&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5cf824f0-2ef8-420b-a26c-f843788c46c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>go_up_btn</value>
      <webElementGuid>10f6fee7-609a-4168-acee-9974e4ac5353</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/GoUp.png</value>
      <webElementGuid>157fc2de-e3bc-4d0b-8539-e3446345df57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>GO UP</value>
      <webElementGuid>112f8e05-4231-43d4-9000-7137bb9dbab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;scrollToTop&quot;)/img[1]</value>
      <webElementGuid>ee6536d9-defb-493f-9f1d-9ea7b4262ab0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='go_up_btn']</value>
      <webElementGuid>5af63e8e-7c9b-4623-9a3e-d5d784bdde88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='scrollToTop']/img</value>
      <webElementGuid>9f940a6a-7193-458c-83b5-a4d0c7f44c43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='GO UP']</value>
      <webElementGuid>72c8bfbb-f287-4913-b1f4-92e2c1d2e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/img</value>
      <webElementGuid>9506058e-1381-4c75-ac4e-577939f557fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'go_up_btn' and @src = 'css/images/GoUp.png' and @alt = 'GO UP']</value>
      <webElementGuid>25b0977f-7ace-481a-8c99-fb8c7c5108e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
