<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_FOLLOW US_follow_twitter</name>
   <tag></tag>
   <elementGuidId>574a06dc-86c9-489c-b0f6-5293120da057</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@name='follow_twitter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[name=&quot;follow_twitter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5af72ebd-b1a4-45af-91e5-7e6cbb40b61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>follow_twitter</value>
      <webElementGuid>26518ad7-697f-4f48-ad3f-32d4f55c7385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>css/images/twitter.png</value>
      <webElementGuid>2cb23922-e768-40cd-9519-8233f5ca7f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>d0fa4245-359e-4f87-8b4a-fab8c5609901</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;follow&quot;)/a[2]/img[1]</value>
      <webElementGuid>aa745406-0ca5-4275-8e68-5b85d4a35fb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@name='follow_twitter']</value>
      <webElementGuid>44db4c02-2ff7-4e46-abbc-27e172c30a36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='follow']/a[2]/img</value>
      <webElementGuid>4527801b-84f2-4ef2-97e2-a5cba478028f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='icon'])[2]</value>
      <webElementGuid>10c9f9f5-4677-4843-a01a-64a77b8886d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>e31bee1a-9e43-442f-9cc6-e37bf799364a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@name = 'follow_twitter' and @src = 'css/images/twitter.png' and @alt = 'icon']</value>
      <webElementGuid>43979b42-7ebf-4dc9-b97b-c68eba1b454a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
