<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_25</name>
   <tag></tag>
   <elementGuidId>71b5ee0c-2c6e-4f8c-96fd-c44454aac388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='25']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#25</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>242596a0-5ca2-4c4e-8206-cf06923c32b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>0445b250-3bed-4e19-99e1-4057056f24e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>98447ef9-6a63-492f-b699-f7f9d8fe2622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>5e1a08b4-bead-4f9a-88c8-d6d498b2e3f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4700</value>
      <webElementGuid>753e5980-39e8-4eeb-85ce-07660de30884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=4700</value>
      <webElementGuid>981fd795-79dc-41e4-97a6-1de56173299d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;25&quot;)</value>
      <webElementGuid>de25a16e-3119-4b06-bb5b-912642d98666</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='25']</value>
      <webElementGuid>6dcadd8a-eea2-48ab-a2f7-6745046ca8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/img</value>
      <webElementGuid>246a6611-a28c-4148-b76a-0cf28ae28ba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '25' and @src = '/catalog/fetchImage?image_id=4700']</value>
      <webElementGuid>a4db9baa-5607-43eb-b775-0e28675fbbd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
