<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_SHOP NOW_16</name>
   <tag></tag>
   <elementGuidId>e193b935-5b18-45b1-90c6-286857c9a894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad1c851f-8907-4b7a-b06c-8e7e81fe40af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>c29a3544-d1d1-4500-9758-42d7f8da03cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>imgProduct</value>
      <webElementGuid>c4d59aea-852a-4c98-b9bb-ca1402419719</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{ outOfStock : product.productStatus == 'OutOfStock' } </value>
      <webElementGuid>572bbb8f-4c94-4e6e-bfe1-71c7502e06a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3100</value>
      <webElementGuid>1f39854c-4edd-4670-89a0-657df1358dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3100</value>
      <webElementGuid>e18fc2de-801c-44c9-a46d-274ec83bd96f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;16&quot;)</value>
      <webElementGuid>ccfc911a-afd2-4286-a352-4bb918331eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='16']</value>
      <webElementGuid>49a27b4c-9d1f-49db-b30f-6de334d6db76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//article[@id='searchPage']/div[3]/div/div/div[2]/ul/li/img</value>
      <webElementGuid>3701dba2-6350-4f01-9e84-2fe246363922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/img</value>
      <webElementGuid>e4f3e74d-74d5-46f9-9db2-b792e6306876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = '16' and @src = '/catalog/fetchImage?image_id=3100']</value>
      <webElementGuid>aa75b4d9-c88b-4911-b4db-b80d03934cec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
