<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DEMO_mobile_search</name>
   <tag></tag>
   <elementGuidId>94cfc714-1c94-40d8-a71a-d5987339636d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mobile_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mobile_search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3930512-32ae-4c99-9889-dd2548005b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_search</value>
      <webElementGuid>4184aa91-6ef3-423e-a404-e90210c541d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b92635cc-3289-40a1-80ba-92bbd669e925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>b605c505-6af3-49dd-9619-292c03869aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>219900ba-6fbf-437d-9f9f-b2054a18afd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>checkEnterKey($event)</value>
      <webElementGuid>58a0a8e5-c532-4aed-88af-ac3a0e5f8942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>autoCompleteValue</value>
      <webElementGuid>e99d54cc-2254-48f8-b8cc-5188757d31e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keyup</name>
      <type>Main</type>
      <value>runAutocomplete()</value>
      <webElementGuid>dd8b193f-91c7-4a0b-8064-3aee5e764ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileSearch&quot;)/input[@class=&quot;roboto-medium ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>3d1fad23-8867-4e55-aeb5-8eebd9c87a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobile_search']</value>
      <webElementGuid>7f9adad8-e760-4fc7-a91a-44611d94d529</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSearch']/input</value>
      <webElementGuid>384897f5-f175-489c-b0d0-723f8759dc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/input</value>
      <webElementGuid>ddd7c536-5aa9-49d6-9642-cc33b0f3276e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobile_search' and @type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>e646c8ff-0315-4310-a931-abc2452c0fa6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
