<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_CHECKOUT  (0.00)_hrefUserIcon</name>
   <tag></tag>
   <elementGuidId>72c55c13-2d4c-4644-976e-1133b22e8145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hrefUserIcon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='hrefUserIcon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>d76447cb-274c-49f7-956a-d5f17910c443</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>hrefUserIcon</value>
      <webElementGuid>b20afd92-2975-43fc-9813-664f23ec29fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>USER</value>
      <webElementGuid>10c61b5f-c4d2-4591-9234-5bf4266943d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hrefUserIcon&quot;)</value>
      <webElementGuid>ff99bef8-6daa-4fe2-8a14-17b3cf621ec3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='hrefUserIcon']</value>
      <webElementGuid>2036aa68-e0f5-455b-9ebf-d8eb06aa9c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='menuUserLink']/a</value>
      <webElementGuid>29c4d81d-d02a-401b-8c23-1496dd763095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0.00'])[1]/following::a[2]</value>
      <webElementGuid>a269bdd1-d257-41c9-8471-31cd773b83dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My account'])[2]/preceding::a[1]</value>
      <webElementGuid>83f764f0-d0fc-4c53-bd19-58d9f6abd6f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My orders'])[2]/preceding::a[1]</value>
      <webElementGuid>98f35a01-15ca-4a3a-9027-5f1f650a312a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li[3]/a/a</value>
      <webElementGuid>21283ea8-8668-461b-b3e2-160e8d9d4523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'hrefUserIcon' and @title = 'USER']</value>
      <webElementGuid>c0e07d15-2f1c-41c9-9740-d70612f64329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
