<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Edit shipping details</name>
   <tag></tag>
   <elementGuidId>ae9e2919-d948-4f36-8264-0b3250ee08ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.blueLink > a.ng-scope</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='userSection']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b3e7e6a5-b808-4850-821a-9fcc65451748</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>425d1742-7799-41bf-b5f9-e828fb516a7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>setUserDetailsEditMode()</value>
      <webElementGuid>3c9d2a71-1fb1-4516-ab39-c84510a867dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>Edit_shipping_Details</value>
      <webElementGuid>019180dd-2fac-411a-8343-e81d31fa1d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>5a131341-cbc4-42bc-99a7-06eff183bb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>073d3347-6d42-42c6-8514-faa67f852715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit shipping details</value>
      <webElementGuid>37f33e5d-2063-4d97-b671-a61a74d28118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userSection&quot;)/div[1]/div[@class=&quot;blueLink&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>855fd039-770c-436f-bf7d-fb2fcda1683a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='userSection']/div/div[2]/a</value>
      <webElementGuid>7a3bd991-1253-4130-8584-be342203e071</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit shipping details')]</value>
      <webElementGuid>121f7dbb-512c-4e0a-a32a-070987f13b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='United States'])[1]/following::a[1]</value>
      <webElementGuid>d0c5242d-2118-421c-b6a9-cb2039dc7420</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Jakarta'])[1]/following::a[1]</value>
      <webElementGuid>7d076ec6-8154-4bd9-978c-d1f597acf2d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHIPPING BY:'])[1]/preceding::a[1]</value>
      <webElementGuid>9757b3cf-0175-45bd-a0df-8610a9a94cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEXT'])[1]/preceding::a[1]</value>
      <webElementGuid>74195499-78f8-47e6-954c-5310933c3576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit shipping details']/parent::*</value>
      <webElementGuid>7201ecb4-d50e-44f6-b087-9aba3540d279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[12]</value>
      <webElementGuid>8ef44f57-7b4d-4ce2-b36f-68e5a54ba581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div[2]/a</value>
      <webElementGuid>d558fd0e-ca99-4500-9293-1993c48774b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = 'Edit shipping details' or . = 'Edit shipping details')]</value>
      <webElementGuid>fd79e89b-ab22-49f5-90e0-2ce46175e89d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
