<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SEE OFFER</name>
   <tag></tag>
   <elementGuidId>c8bfbfa7-5ca0-4232-89ed-282414e0e0b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#see_offer_btn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='see_offer_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c0bd6c47-0b49-436f-9b18-074d4eb040a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>see_offer_btn</value>
      <webElementGuid>78b9f7c8-6108-4b29-a9c1-ca0a286e2bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>SEE_OFFER</value>
      <webElementGuid>676586cd-645a-48e1-9d20-acd0350ffc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82398bb8-4a80-4d01-a2f8-3351d712a159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>68ee2b10-da18-4b7a-a183-fb3d54c4d710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SEE OFFER</value>
      <webElementGuid>e1dd5ca2-5519-468a-93b3-1ac4ecac370f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;see_offer_btn&quot;)</value>
      <webElementGuid>13047eb1-9701-4903-ae66-14166392b730</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='see_offer_btn']</value>
      <webElementGuid>9652eae6-85a1-4eaf-a6c1-b98b9269f380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div-special-offer']/div/a/button</value>
      <webElementGuid>9264e423-9000-4408-bcf0-79a4c75450cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HP Pavilion 15z Touch Laptop'])[1]/following::button[1]</value>
      <webElementGuid>2e436308-810b-4ce5-8f58-f89a58a90a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE THE NEW DESIGN'])[1]/following::button[1]</value>
      <webElementGuid>ce86f505-381b-4d3f-818b-e2e14ccfb2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALL YOU WANT FROM A TABLET'])[1]/preceding::button[1]</value>
      <webElementGuid>94d3eeee-503a-4e8b-9fcd-0e09416b38ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EXPLORE NOW'])[1]/preceding::button[1]</value>
      <webElementGuid>0a9fd8a2-51db-4d05-8184-bd37fff6cf74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SEE OFFER']/parent::*</value>
      <webElementGuid>1e94966e-b6d6-4f22-9bb2-4193ab5406ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/button</value>
      <webElementGuid>68f4afaf-14ee-48d2-946a-0dc9ddac0648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'see_offer_btn' and (text() = 'SEE OFFER' or . = 'SEE OFFER')]</value>
      <webElementGuid>79af3c8e-81a9-4fe0-8f04-3c2d4b00fd88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
