<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_SIGN IN WITH FACEBOOK_closeBtn loginPop_5cda56</name>
   <tag></tag>
   <elementGuidId>d723ebfd-5cb1-40a2-a34b-df569ed4078c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.closeBtn.loginPopUpCloseBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>092e7f95-f06d-41c3-a611-39fe3ce6334a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeBtn loginPopUpCloseBtn</value>
      <webElementGuid>dd7fcab8-d609-42f7-a16d-643012fe16ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/login-modal[1]/div[@class=&quot;PopUp&quot;]/div[1]/div[@class=&quot;closeBtn loginPopUpCloseBtn&quot;]</value>
      <webElementGuid>d11322bb-ccc9-4f9b-ba00-f79ffb9f300a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]</value>
      <webElementGuid>0bcddbe8-97be-420a-ab8f-7adb3315976e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
