<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_HOME</name>
   <tag></tag>
   <elementGuidId>767ea5ad-6075-4685-b443-6fcc67be480e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'HOME')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.pages.categoryDataFixedNav > a.ng-scope</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8853a72b-2a84-4494-b20f-8c6c8e308f7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>translate</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>0438dd03-2ace-4fb8-ab0d-1f2b1ff30b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#/</value>
      <webElementGuid>ba4205d4-e252-4a2b-8424-2885097ca54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-scope</value>
      <webElementGuid>10f90156-1174-4943-b274-1c9356056f54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HOME</value>
      <webElementGuid>fbfa0a7f-834e-426c-9fa7-6490b54a47a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ng-scope&quot;]/div[@class=&quot;uiview ng-scope&quot;]/section[@class=&quot;ng-scope&quot;]/article[1]/div[2]/nav[@class=&quot;pages categoryDataFixedNav&quot;]/a[@class=&quot;ng-scope&quot;]</value>
      <webElementGuid>21eb7c18-5d64-4fb7-85de-ddf863e62063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'HOME')]</value>
      <webElementGuid>b1651217-e03a-451d-83f6-80ac91d7256f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BUY NOW'])[1]/following::a[1]</value>
      <webElementGuid>46af61a3-88d3-48de-a6ca-a70688192f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TABLETS'])[1]/preceding::a[1]</value>
      <webElementGuid>1fcfbc60-3eea-4ebf-9e52-a20eba5d8975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TABLETS'])[2]/preceding::a[2]</value>
      <webElementGuid>7faeb2d5-a1c5-4f10-b3c4-b948a99346df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='HOME']/parent::*</value>
      <webElementGuid>4a5743ff-03de-4610-989c-18c1200e0ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#/')])[5]</value>
      <webElementGuid>7c2f4de9-1c70-4df5-aa42-a80f2fe56c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/a</value>
      <webElementGuid>c1066bd4-5680-4d6d-97e5-8d246e4f34cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#/' and (text() = 'HOME' or . = 'HOME')]</value>
      <webElementGuid>c26ca327-c878-4ec3-86a2-e19ffea352c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
