<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_DISPLAY</name>
   <tag></tag>
   <elementGuidId>81ec2ae4-2900-4ae0-b61f-a2592db86e41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionAttrib0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accordionAttrib0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>7f14fe90-9a6f-419f-aa4e-89b5ec947258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>fb03c0f2-67ed-486a-aebe-a02873dc73cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-binding</value>
      <webElementGuid>af66efb4-6dd8-42f8-8f58-81c170e43296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionAttrib0</value>
      <webElementGuid>c601584a-2a01-4806-baa3-afbff9bcab28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionAttrib' + $index)</value>
      <webElementGuid>1ff871d3-e5f2-472b-bf92-519744a1c610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>a01c755a-4973-4e63-b8fd-049786cd703a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        DISPLAY
                    </value>
      <webElementGuid>ab9d8aff-3257-415f-8a65-44f7d53721ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionAttrib0&quot;)</value>
      <webElementGuid>adc8bd30-659b-4838-b4ce-cdad1ad2a540</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionAttrib0']</value>
      <webElementGuid>5bd20ac2-587a-4c80-98c4-97a504ab2f6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[2]/h4</value>
      <webElementGuid>c1ea269d-9cfc-46b4-ab5a-aa023c8742c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PRICE'])[1]/following::h4[1]</value>
      <webElementGuid>474e9a0f-9f7b-43a0-ad42-2e0ee67c04f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/following::h4[2]</value>
      <webElementGuid>81b4cbbb-c1af-4951-816b-1a8dfe0caaf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PROCESSOR'])[1]/preceding::h4[1]</value>
      <webElementGuid>4a109e99-726d-4281-b2a7-d35d52593333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DISPLAY']/parent::*</value>
      <webElementGuid>68b180bc-1634-403d-b5bd-7a2f825636e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/h4</value>
      <webElementGuid>dec77c6c-c6b1-402b-ae2d-c88d9bca56c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionAttrib0' and (text() = '
                        DISPLAY
                    ' or . = '
                        DISPLAY
                    ')]</value>
      <webElementGuid>0b7d0b5a-601a-4b75-965f-c87a703076c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
