<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_PROCESSOR</name>
   <tag></tag>
   <elementGuidId>b4dced69-a410-4980-b277-64ad81836a64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h4[@id='accordionAttrib1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#accordionAttrib1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>89e778c7-991d-4d92-a3da-09db9b6930f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>a15f52d7-f7bb-4c0a-8067-62991ea20dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accordion roboto-regular arrowDown ng-binding</value>
      <webElementGuid>85902a9a-83ef-4ccf-9171-32de3b6e4683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>accordionAttrib1</value>
      <webElementGuid>f10d545e-e2bd-4a4f-9c05-1bcea41b36ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleColapse('accordionAttrib' + $index)</value>
      <webElementGuid>8a897ed6-4abb-4375-af36-cef3ea3ca3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>link</value>
      <webElementGuid>f19607b3-ebbd-4300-a94c-f0a644aa24a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        PROCESSOR
                    </value>
      <webElementGuid>1b97f5c8-8a15-4a67-a9d3-41c8863c4c82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordionAttrib1&quot;)</value>
      <webElementGuid>1a5fcf72-d478-4c1a-9672-ffbf29ced2f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h4[@id='accordionAttrib1']</value>
      <webElementGuid>6df924dd-468f-4092-b967-53eb00a90eaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[3]/h4</value>
      <webElementGuid>5d5cab8e-bff6-4de9-8f6a-05ab3344c11f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DISPLAY'])[1]/following::h4[1]</value>
      <webElementGuid>a7aa08d7-8806-4908-bea0-33663d4494c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intel® Atom® Z3795 (1.6 GHz, up to 2.39 GHz using Intel Burst Technology, 2 MB cache, 4 cores)'])[1]/preceding::h4[1]</value>
      <webElementGuid>6f988da1-bfca-4f36-87be-b872bae95b56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COLOR'])[1]/preceding::h4[1]</value>
      <webElementGuid>d1862a7c-aa94-4e16-9739-0477f1511920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PROCESSOR']/parent::*</value>
      <webElementGuid>909d9c0f-49c7-41c0-b6f5-ba5a978c0a9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/h4</value>
      <webElementGuid>462e7ddc-c348-499d-8868-f5ba0c7d4369</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[@href = 'javascript:void(0)' and @id = 'accordionAttrib1' and (text() = '
                        PROCESSOR
                    ' or . = '
                        PROCESSOR
                    ')]</value>
      <webElementGuid>223fa0c5-ba5a-4389-8af0-5792019b6f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
