<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_WIRELESS TECHNOLOGY_wireless_technology_0</name>
   <tag></tag>
   <elementGuidId>75086d15-a486-4763-bab3-73288df8d698</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='wireless_technology_0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#wireless_technology_0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6c303c67-369a-4c7d-96c9-245cd3d1a085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>wireless_technology_0</value>
      <webElementGuid>10242aa2-080c-443d-af19-1ab5da1b0534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ecccb640-d076-467d-b34b-cd3ebbd0261b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>item.selected</value>
      <webElementGuid>ec803dfd-4ee8-4db3-9eb5-1d68f11a5999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>includeProducts(attrVal, attrib.name)</value>
      <webElementGuid>bb460e02-0d08-42dd-a62c-5dcda9593d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>wireless_technology_0</value>
      <webElementGuid>7e8523a9-e5b0-4546-b346-28da725af9ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>5b7999ff-c7ab-446e-a9dc-c4e270bac907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wireless_technology_0&quot;)</value>
      <webElementGuid>9176e9c0-7e1c-4f65-ad57-171c5f0cabe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='wireless_technology_0']</value>
      <webElementGuid>c2dc02d8-a131-4712-b600-bffdb60a2c36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSlide']/ul/li[5]/div/div/div/input</value>
      <webElementGuid>2f9f0e9c-ad7a-4fa0-950c-0ceae97b50dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/div/div/div/input</value>
      <webElementGuid>8d972c6d-798e-4adf-8d06-f6aaa9362c0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'wireless_technology_0' and @type = 'checkbox' and @id = 'wireless_technology_0']</value>
      <webElementGuid>8536c0bb-b8c4-458d-95f4-d7845913e2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
