<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1</name>
   <tag></tag>
   <elementGuidId>70211593-fbf3-4feb-bde6-95a7e9de3311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='lengthAllImages']/div[3]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>616b9351-2b58-494f-930f-7a164170b485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3103</value>
      <webElementGuid>881e33bd-4e8f-4373-8909-af2a80411a77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/catalog/fetchImage?image_id=3103</value>
      <webElementGuid>f9c99d5a-ac90-43c0-9128-d5d03b89404f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lengthAllImages&quot;)/div[@class=&quot;imageAlias ng-scope&quot;]/img[1]</value>
      <webElementGuid>2926c6b8-1138-42c0-bd85-18d811328c47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lengthAllImages']/div[3]/img</value>
      <webElementGuid>152935bb-8f7d-4e58-8ef6-5fdc8bc2be87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[3]/img</value>
      <webElementGuid>b72f17d8-9554-4fd7-8c1e-671964db97aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/catalog/fetchImage?image_id=3103']</value>
      <webElementGuid>54629c50-d732-41e1-826f-f55731bc20c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
