<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DEMO_mobile_search</name>
   <tag></tag>
   <elementGuidId>75a83948-fc76-4201-994a-9fc231e8227c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='mobile_search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;mobile_search&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2b0b859-645a-4f54-a3d0-9f3d5e7d39b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>mobile_search</value>
      <webElementGuid>1a6dd679-d6f8-4037-b377-5f0c82451017</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5d4056b0-953b-4d1c-b90b-7076fd14793a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>roboto-medium ng-pristine ng-untouched ng-valid</value>
      <webElementGuid>c1e38a0f-0dd7-4d15-ae63-d01d318a472f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>6faed5fe-183e-4fde-85f2-6c3d9813db6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keypress</name>
      <type>Main</type>
      <value>checkEnterKey($event)</value>
      <webElementGuid>0b48f334-7c3b-4d58-a55d-675f996a97be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>autoCompleteValue</value>
      <webElementGuid>f1e33896-7ff4-4626-9bc8-229a618a8ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-keyup</name>
      <type>Main</type>
      <value>runAutocomplete()</value>
      <webElementGuid>eae83349-7606-4ebb-82c7-ae257bb16171</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mobileSearch&quot;)/input[@class=&quot;roboto-medium ng-pristine ng-untouched ng-valid&quot;]</value>
      <webElementGuid>95d71f46-dfaa-47f7-b2c1-c45caa01fdf2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='mobile_search']</value>
      <webElementGuid>98717761-3c0c-4727-b12b-b74e2ca36019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mobileSearch']/input</value>
      <webElementGuid>8b408023-b0c7-4b7b-b703-88d7a58bee06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//article/div/input</value>
      <webElementGuid>db6c4141-ee6c-493f-943f-ae8b24165a12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'mobile_search' and @type = 'text' and @placeholder = 'Search']</value>
      <webElementGuid>a37fe5e4-045c-4616-9973-e8aae083ccf9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
